let userScore = 0;
let compScore = 0;

const choices = document.querySelectorAll(".choice");
const msg= document.querySelector("#msg");

const userScorePara= document.querySelector("#user-score");
const compScorePara= document.querySelector("#comp-score");

const genCompChoice= () => {
    const options = ["rock", "paper", "scissors"];
    const randomIdx = Math.floor(Math.random()*3);
    return options[randomIdx];
    //rock, paper, and scissors generator for computer
}


const drawGame = () =>{
    console.log("Game was draw.")
    msg.innerText = "Game is Draw";
}
 

const showWinner = (userWin) => {
    if (userWin){
        userScore++;
        userScorePara.innerText = userScore; 
        //for updating userScore
        console.log("You win!"); 
        //for checking in the backend
        msg.innerText= "User Wins!";
    } else{
        compScore++
        compScorePara.innerText = compScore;
        console.log("You lost!");
        msg.innerText= "User Lost!";
    }
}


const playGame = (userChoice) => {
    console.log("user choice = ", userChoice);
    //To generate computer choice
    const compChoice = genCompChoice();
    console.log("comp choice = ", compChoice);

    if (userChoice === compChoice){
        //Game=Draw
        drawGame();
    } else{
        let userWin = true;
        if (userChoice === "rock"){
            //scissor or paper generated by computer
            userWin = compChoice === "paper" ? false : true;
        } else if (userChoice === "paper"){
            // rock or scissor generated by computer
            userWin= compChoice === "scissors"? false:true;
            //making it compact using ternary operator 
        } else{
            //computer can select rock or paper
            userWin= compChoice === "rock"? false:true;
        }
        showWinner(userWin);
    }
}


choices.forEach((choice)=> {
    choice.addEventListener("click", () => { 
        const userChoice= choice.getAttribute("id");
        playGame(userChoice);
    });
});